### ISSUE TITLE
Possible POP documentation error

### ISSUE THREAD

**Issue by danieldmulkey** [indranilsinharoy/PyZDDE#68]
Hello,

First off, this package is excellent. Thank you for making and sharing it. 

Comparing the documentation on paramN and fparamN in help(ln.zSetPOPSettings) suggests that the parameters are ordered as you read them in Zemax. The discrepancy I saw is that Zemax 15.5 SP2 would then suggest that fparamN 1 and 2 are Tilt About X (deg) and Y (deg) respectively but PyZDDE seems think that 1 and 2 are Waist X and Waist Y. That said, the way it is now makes paramN and fparamN behave more similarly if I remember correctly. 

That caused me some confusion but I was able to sort out the difference after some examination. I just figured I'd throw in a request for that to be clarified or changed for future users. 

Cheers!

**Comment by indranilsinharoy** [comment]
Hi @danieldmulkey ,

Thank you very much for your kind words. 

I'm not quite sure I understood your question. The function `ln.zSetPOPSettings()` has two separate arguments for the parameters `Tilt About X` and `Tilt About Y`, which uses `POP_TILTX` and `POP_TILTY` (along with the specific values) to send message to Zemax. In fact `fparamN1` and `fparamN2`, indeed, are for `WaistX` and `WaistY`, as for as I understand reading the Zemax manual. 

> The discrepancy I saw is that Zemax 15.5 SP2 would then suggest that fparamN 1 and 2 are Tilt About X (deg) and Y (deg) respectively 

I may still be making a mistake. Therefore, could you please point me to the source which suggest the above?

Thank you very much.
Best regards.

**Comment by danieldmulkey** [comment]
Ah! Then I must've misunderstood. I missed POP_TILTX/Y so I thought those
were supposed to be accounted for in the fparamN tuple. I was assuming the
parameters should be ordered as they appear in the POP Zemax window and on
my version it starts with the tilts. My only source was the Zemax POP
window.

Cheers,

On Mar 11, 2017 10:33 PM, "Indranil Sinharoy" <notifications@github.com>
wrote:

Hi @danieldmulkey <https://github.com/danieldmulkey> ,

Thank you very much for your kind words.

I'm not quite sure I understood your question. The function
ln.zSetPOPSettings() has two separate arguments for the parameters Tilt
About X and Tilt About Y, which uses POP_TILTX and POP_TILTY (along with
the specific values) to send message to Zemax. In fact fparamN1 and fparamN2,
indeed, are for WaistX and WaistY, as for as I understand reading the Zemax
manual.

The discrepancy I saw is that Zemax 15.5 SP2 would then suggest that
fparamN 1 and 2 are Tilt About X (deg) and Y (deg) respectively

I may still be making a mistake. Therefore, could you please point me to
the source which suggest the above?

Thank you very much.
Best regards.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/indranilsinharoy/PyZDDE/issues/68#issuecomment-285925680>,
or mute the thread

**Comment by indranilsinharoy** [comment]
Hi @danieldmulkey 

Fixing that was easy ;-). I will close the issue.

**Comment by danieldmulkey** [comment]
Thank you!
