### ISSUE TITLE
zSetMulticon support string values?

### ISSUE THREAD

**Issue by danieldmulkey** [indranilsinharoy/PyZDDE#72]
Hello,

Does ln.zSetMulticon() support strings for the value argument? The documentation suggests only floats, but then I don't see how you could enter any configuration values for 'GLSS' in that case. Is there different method I'm not aware of?

Cheers,

**Comment by indranilsinharoy** [comment]
Hi @danieldmulkey,

There are two ways of using the `zSetMulticon()` method (described in the docstring). If the `config = 0`, then, this function is used to set the operand type (string, like 'GLSS`, `THIC` etc.) and number data. I hope that helps.

**Comment by danieldmulkey** [comment]
The issue I had wasn't in setting operand type, I wasn't able to set a
string value for an operand. So, for example, I could set 'THIC' to 5 and 3
but not 'GLSS' to 'N-BK7' and 'SF-5'. It gave some error saying that
formatter 'g' had no meaning for strings, as it was expecting a number.

Cheers,
